# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf6613b1dd36e3b4d1b6767b7c98268926a44732672401d27f285cc2d9d94466a543ed9a811c1dab2f467e4e361b694b1c8e959263151b4d6f92ed1882381ac0

test:
  secret_key_base: 68a12d620c55a434f9b1a6e2ef9854ce64a5c6c1eed1621febe30340ef7c6644936d2dde257d5e286fa1de547149f7980474b0e033b01e647d7f9b0f3086b6a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
